# Generated by Django 5.1 on 2024-10-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(max_length=255)),
                ('s_mobno', models.CharField(max_length=255)),
                ('s_email', models.CharField(max_length=255)),
                ('s_address', models.CharField(max_length=255)),
                ('s_city', models.CharField(max_length=255)),
            ],
        ),
    ]
